# Site identity
title: "Ucchwas Talukder"
email: "ucchwas09@gmail.com"
description: >
  PhD Candidate at Texas Tech University. Real‑time health‑monitoring
  via embedded IoT, ultra‑low‑power sensors, & edge‑AI.
baseurl: ""                     # no subdirectory
url: "https://ucchwas09.github.io"

# Pull Minimal Mistakes from GitHub
remote_theme: "mmistakes/minimal-mistakes"

# Plugins (no theme gem needed)
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# Top nav – the pages you’ve created
header_pages:
  - index.md
  - about.md
  - research.md
  - projects.md
  - publications.md
  - achievements.md

# Sass settings
sass:
  style: compressed
  load_paths:
    - assets/css

# Default front‑matter for your pages
defaults:
  - scope:
      path: ""      # all files
      type: "pages"
    values:
      layout: single
      author_profile: false
      read_time: false

# Footer social links
footer:
  social:
    - title: "GitHub"
      url: https://github.com/Ucchwas
    - title: "LinkedIn"
      url: https://www.linkedin.com/in/ucchwas-talukder-utsha-98024518b/
    - title: "Google Scholar"
      url: https://scholar.google.com/citations?user=5d2l7uQAAAAJ
