title: "Ucchwas Talukder"
description: "PhD candidate in Computer Science, working on real-time health monitoring solutions"
minimal_mistakes_skin: "default"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jemoji
  - jekyll-gist

include:
  - "_pages"

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
